[package]
name = "lispy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.clippy]
pedantic = "warn"
missing_errors_doc = "allow"

[dependencies]
nom = "7.1.3"
